[connection]
id=Datio MX
uuid={{ 999999999999999999999 | random | to_uuid }}
type=vpn
permissions=

[vpn]
auth=SHA1
ca={{ dropbox_dir }}/vpn/datio/vpn-mexico-bancomer.p12
cert={{ dropbox_dir }}/vpn/datio/vpn-mexico-bancomer.p12
cert-pass-flags=1
cipher=AES-128-CBC
connection-type=password-tls
dev=tun
key={{ dropbox_dir }}/vpn/datio/vpn-mexico-bancomer.p12
password-flags=1
remote=200.66.87.82:1195:udp
remote-cert-tls=server
ta={{ dropbox_dir }}/vpn/datio/vpn-mexico-bancomer.key
ta-dir=1
username={{ ansible_user }}
verify-x509-name=name:pfsense1.mx.datio
service-type=org.freedesktop.NetworkManager.openvpn

[ipv4]
dns-search=
method=auto
never-default=true

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
